import { defineConfig } from 'cypress'

/**
 * Cypress configuration for the Music-Tech Shop E2E suite.
 *
 * Target application: https://music-tech-shop.vercel.app
 * (Next.js + React + Tailwind + shadcn/ui hosted on Vercel)
 */
export default defineConfig({
  // HTML report generated by cypress-mochawesome-reporter (see Fase 8).
  reporter: 'cypress-mochawesome-reporter',
  reporterOptions: {
    charts: true,
    reportPageTitle: 'Music-Tech Shop — Cypress Report',
    embeddedScreenshots: true,
    inlineAssets: true,
    reportDir: 'cypress/report',
    overwrite: false,
    html: true,
    json: false,
  },

  e2e: {
    // Target application base URL.
    baseUrl: 'https://music-tech-shop.vercel.app',

    // Desktop viewport — header search bar is `hidden md:block`, so a mobile
    // viewport would hide it and break search tests.
    viewportWidth: 1280,
    viewportHeight: 720,

    // The app hydrates client-side; give assertions a bit of headroom.
    defaultCommandTimeout: 10000,

    // Retry flaky runs (the app is hosted on Vercel and may have cold starts).
    retries: {
      runMode: 2,
      openMode: 0,
    },

    // Videos are large and rarely useful with screenshots enabled.
    video: false,
    screenshotOnRunFailure: true,

    specPattern: 'cypress/e2e/**/*.cy.ts',

    setupNodeEvents(on, config) {
      // Register the Mochawesome reporter hooks.
      require('cypress-mochawesome-reporter/plugin')(on)

      // Log the resolved baseUrl so it is visible in the runner output.
      // eslint-disable-next-line no-console
      console.log(`[cypress] baseUrl = ${config.baseUrl}`)

      return config
    },
  },

  env: {
    // Private configuration values (not exposed to application code).
    // The Music-Tech Shop app ships these demo credentials in its bundle, so
    // they are not real secrets — but we keep them in `env` to follow the
    // Cypress 15 convention of not reading sensitive values via Cypress.env().
    adminEmail: 'admin@test.com',
    adminPassword: 'admin123',
    customerEmail: 'user@test.com',
    customerPassword: 'user123',

    // API base path discovered via /api-test harness. The app exposes its
    // backend under /api/* — keep this as a single source of truth.
    apiBaseUrl: 'https://music-tech-shop.vercel.app/api',
  },

  // Public configuration values accessible from browser code via Cypress.expose().
  // Used by specs/commands that need values synchronously (e.g. inside cy.session).
  expose: {
    adminEmail: 'admin@test.com',
    adminPassword: 'admin123',
    customerEmail: 'user@test.com',
    customerPassword: 'user123',
  },

  // Cypress 15: disallow legacy Cypress.env() reads from browser code so the
  // suite fails loud if anything accidentally reaches into private env.
  allowCypressEnv: false,
})
